perc/models.py
from perc import db, lm
from flask_login import UserMixin


class Annotation(db.Model):
    __tablename__ = 'annotations'

    annotation_guid = db.Column(db.String(32), primary_key=True)
    reading_guid = db.Column(db.ForeignKey('readings.reading_guid'), nullable=False)
    annotation = db.Column(db.Text)

    reading = db.relationship('Reading', primaryjoin='Annotation.reading_guid == Reading.reading_guid',
                              backref='annotations')


class Asset(db.Model):
    __tablename__ = 'assets'
    __table_args__ = (
        db.CheckConstraint("(model)::text <> ''::text"),
        db.CheckConstraint("(serial)::text <> ''::text"),
        db.UniqueConstraint('model', 'serial')
    )

    asset_guid = db.Column(db.String(32), primary_key=True)
    asset_type = db.Column(db.SmallInteger, nullable=False)
    model = db.Column(db.String(32), nullable=False)
    serial = db.Column(db.String(32), nullable=False)
    active = db.Column(db.Boolean)
    deleted = db.Column(db.Boolean)
    asset_password = db.Column(db.String(20))
    notes = db.Column(db.Text)


class LicenseInUse(db.Model):
    __tablename__ = 'license_in_use'

    license_in_use_guid = db.Column(db.String(32), primary_key=True)
    computer_name = db.Column(db.Text, nullable=False)
    user_guid = db.Column(db.ForeignKey('users.user_guid'), nullable=False)
    license_guid = db.Column(db.ForeignKey('licenses.license_guid'), nullable=False)
    time_stamp = db.Column(db.DateTime, nullable=False)

    license = db.relationship('License', primaryjoin='LicenseInUse.license_guid == License.license_guid',
                              backref='license_in_uses')
    user = db.relationship('User', primaryjoin='LicenseInUse.user_guid == User.user_guid', backref='license_in_uses')


class License(db.Model):
    __tablename__ = 'licenses'

    license_guid = db.Column(db.String(32), primary_key=True)
    license_type = db.Column(db.SmallInteger, nullable=False)
    license_serial = db.Column(db.String(20))
    version = db.Column(db.String(20))
    date_applied = db.Column(db.DateTime, nullable=False)
    logins_remaining = db.Column(db.Integer)
    license_id = db.Column(db.Text, nullable=False)
    deleted = db.Column(db.Boolean)


class Location(db.Model):
    __tablename__ = 'locations'
    __table_args__ = (
        db.CheckConstraint("(location_name)::text <> ''::text"),
    )

    location_guid = db.Column(db.String(32), primary_key=True)
    location_name = db.Column(db.String(20), nullable=False, unique=True)
    active = db.Column(db.Boolean)
    deleted = db.Column(db.Boolean)
    notes = db.Column(db.Text)


class LogSession(db.Model):
    __tablename__ = 'log_sessions'

    log_session_guid = db.Column(db.String(32), primary_key=True)
    session_start = db.Column(db.DateTime, nullable=False)
    session_end = db.Column(db.DateTime)
    logging_interval = db.Column(db.Integer, nullable=False)
    logger_guid = db.Column(db.ForeignKey('assets.asset_guid'), nullable=False)
    user_guid = db.Column(db.ForeignKey('users.user_guid'), nullable=False)
    session_type = db.Column(db.SmallInteger, nullable=False)
    computer_name = db.Column(db.Text, nullable=False)

    asset = db.relationship('Asset', primaryjoin='LogSession.logger_guid == Asset.asset_guid', backref='log_sessions')
    user = db.relationship('User', primaryjoin='LogSession.user_guid == User.user_guid', backref='log_sessions')


class Reading(db.Model):
    __tablename__ = 'readings'

    reading_guid = db.Column(db.String(32), primary_key=True)
    reading = db.Column(db.Float(53), nullable=False)
    reading_type = db.Column(db.SmallInteger, nullable=False)
    time_stamp = db.Column(db.DateTime, nullable=False)
    log_session_guid = db.Column(db.ForeignKey('log_sessions.log_session_guid'), nullable=False)
    sensor_guid = db.Column(db.ForeignKey('assets.asset_guid'), nullable=False)
    location_guid = db.Column(db.ForeignKey('locations.location_guid'), nullable=False)
    channel = db.Column(db.SmallInteger, nullable=False)
    max_alarm = db.Column(db.Boolean)
    max_alarm_value = db.Column(db.Float(53))
    min_alarm = db.Column(db.Boolean)
    min_alarm_value = db.Column(db.Float(53))
    compromised = db.Column(db.Boolean)


class SensorParameter(db.Model):
    __tablename__ = 'sensor_parameters'

    log_session_guid = db.Column(db.ForeignKey('log_sessions.log_session_guid'), primary_key=True, nullable=False)
    channel = db.Column(db.SmallInteger, primary_key=True, nullable=False)
    parameter_name = db.Column(db.String(128), primary_key=True, nullable=False)
    parameter_value = db.Column(db.String(128), nullable=False)

    log_session = db.relationship('LogSession', primaryjoin='SensorParameter.log_session_guid == '
                                                            'LogSession.log_session_guid', backref='sensor_parameters')


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    __table_args__ = (
        db.CheckConstraint("(login_name)::text <> ''::text"),
    )

    @property
    def id(self):
        """Return an identifier."""
        return self.user_guid

    user_guid = db.Column(db.String(32), primary_key=True)
    login_name = db.Column(db.String(32), nullable=False, unique=True)
    first_name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))
    user_password = db.Column(db.String(64))
    user_group = db.Column(db.SmallInteger)
    permissions = db.Column(db.BigInteger)
    active = db.Column(db.Boolean)
    deleted = db.Column(db.Boolean)
    change = db.Column(db.Boolean)
    notes = db.Column(db.Text)


class Version(db.Model):
    __tablename__ = 'versions'

    db_version = db.Column(db.String(20), primary_key=True)
    client_version = db.Column(db.String(20))


@lm.user_loader
def load_user(id):
    return User.query.get(id)

perc/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField, SelectField, DateField, DecimalField
from wtforms.validators import DataRequired
from perc import db
from perc.models import Location


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Save Credentials')
    submit = SubmitField('Submit')


class ReportForm(FlaskForm):
    location = SelectField(label='Location', coerce=int)
    '''
    criteria = SelectField('Specifications',
                           choices=[('Pass a dictionary with Main lab parameters!!', 'Main Lab'),
                                    ('Pass a dictionary with Cold Room parameters!!', 'Cold Room'),
                                    ('Allow user to input custom environment parameters!!', 'Custom')])
    '''
    start_date = DateField('<b>Start Date</b> e.g. 2017-03-26',
                           validators=[DataRequired()])
    end_date = DateField('<b>End Date</b> e.g. 2017-03-28',
                         validators=[DataRequired()])
    temperature = DecimalField('Temperature', validators=[DataRequired()], default=73.00)
    temp_tol = DecimalField('Temperature Tolerance', validators=[DataRequired()], default=6.00)
    humidity = DecimalField('Humidity', validators=[DataRequired()], default=35.00)
    humid_tol = DecimalField('Humidity Tolerance', validators=[DataRequired()], default=15.00)
    submit = SubmitField()

    def pop_loc(self):
        locations = db.session.query(Location).all()
        loc_choices = [loc.location_name for loc in locations]
        loc_names = list(enumerate(loc_choices))
        self.location.choices = loc_names

perc/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view ='main.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    lm.init_app(app)

    from perc.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

perc/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from perc.main import views, errors

perc/main/views.py
from datetime import datetime
from flask import render_template, redirect, url_for, request, flash
from flask_login import login_required, login_user, logout_user
from perc.main import main
from perc.main.forms import LoginForm, ReportForm
from perc.models import User
from process import Report


@main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@main.errorhandler(500)
def page_not_found(e):
    return render_template('500.html'), 500


@main.route('/')
def index():
    return render_template('index.html', current_time=datetime.utcnow())


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login_name=form.username.data).first()
        if user is None or form.password.data != 'LogWare':
            flash('Not Authorized.')
            return redirect(url_for('main.login', **request.args))
        login_user(user, form.remember_me.data)
        return redirect(request.args.get('next') or url_for('main.dashboard'))
    return render_template('login.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')


@main.route('/report', methods=['GET', 'POST'])
@login_required
def report():
    form = ReportForm()
    form.pop_loc()
    if request.method == 'POST' and form.validate():
        s = Report(request.form['location'],
                   request.form['temperature'],
                   request.form['humidity'],
                   request.form['temp_tol'],
                   request.form['humid_tol'],
                   request.form['start_date'],
                   request.form['end_date'])

        return render_template('summary_report.html',
                               loc_name=s.get_location_name(),
                               start_date=s.start_date,
                               end_date=s.end_date,
                               temperature=s.temperature,
                               temp_tol=s.temperature_tolerance,
                               humidity=s.humidity,
                               humid_tol=s.humidity_tolerance,
                               report_data=s.generate_summary(),
                               current_time=datetime.utcnow())

    return render_template('report.html', form=form)

perc/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}PERC{% endblock %}

{% block head %}
{{ super() }}
<link rel='shortcut icon' href='{{ url_for('static', filename='favicon.ico') }}' type='image/x-icon'>
<link rel='icon' href='{{ url_for('static', filename='favicon.ico') }}' type='image/x-icon'>
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">PERC</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
              <li><a href="#">Locations</a></li>
              <li><a href="#">Sessions</a></li>
              <li><a href="{{ url_for('main.report') }}">Reports</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
              
              {% if current_user.is_authenticated %}
                  <li><a href="#">Welcome, {{ current_user.login_name }}</a></li>
                  <li><a href="{{ url_for('main.logout') }}">Logout</a><li>
              {% else %}
                  <li><a href="{{ url_for('main.login') }}">Login</a></li>
              {% endif %}
              
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
{% endblock %}

{% block content %}
<div class = "container">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-warning" role="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{{ message }}
	</div>
	{% endfor %}
	{% block page_content %}{% endblock %}
</div>
{% endblock  %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

perc/templates/dashboard.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}PERC | Dashboard{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='dashboard.css')}}">
{% endblock %}

{% block content %}
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">PERC</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li class="active"><a href="{{ url_for('main.index') }}">Home</a></li>
              <li><a href="#">Locations</a></li>
              <li><a href="#">Sessions</a></li>
              <li><a href="{{ url_for('main.report') }}">Reports</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">

              {% if current_user.is_authenticated %}
                  <li><a href="#">Welcome, {{ current_user.login_name }}</a></li>
                  <li><a href="{{ url_for('main.logout') }}">Logout</a><li>
              {% else %}
                  <li><a href="{{ url_for('main.login') }}">Login</a></li>
              {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>
<div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Welcome, {{ current_user.login_name }}</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>QA</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Torque</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>K3</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>K6</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>68D</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-4 placeholder">
              <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>K8</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>Integer</td>
                  <td>nec</td>
                  <td>odio</td>
                  <td>Praesent</td>
                </tr>
                <tr>
                  <td>1,003</td>
                  <td>libero</td>
                  <td>Sed</td>
                  <td>cursus</td>
                  <td>ante</td>
                </tr>
                <tr>
                  <td>1,004</td>
                  <td>dapibus</td>
                  <td>diam</td>
                  <td>Sed</td>
                  <td>nisi</td>
                </tr>
                <tr>
                  <td>1,005</td>
                  <td>Nulla</td>
                  <td>quis</td>
                  <td>sem</td>
                  <td>at</td>
                </tr>
                <tr>
                  <td>1,006</td>
                  <td>nibh</td>
                  <td>elementum</td>
                  <td>imperdiet</td>
                  <td>Duis</td>
                </tr>
                <tr>
                  <td>1,007</td>
                  <td>sagittis</td>
                  <td>ipsum</td>
                  <td>Praesent</td>
                  <td>mauris</td>
                </tr>
                <tr>
                  <td>1,008</td>
                  <td>Fusce</td>
                  <td>nec</td>
                  <td>tellus</td>
                  <td>sed</td>
                </tr>
                <tr>
                  <td>1,009</td>
                  <td>augue</td>
                  <td>semper</td>
                  <td>porta</td>
                  <td>Mauris</td>
                </tr>
                <tr>
                  <td>1,010</td>
                  <td>massa</td>
                  <td>Vestibulum</td>
                  <td>lacinia</td>
                  <td>arcu</td>
                </tr>
                <tr>
                  <td>1,011</td>
                  <td>eget</td>
                  <td>nulla</td>
                  <td>Class</td>
                  <td>aptent</td>
                </tr>
                <tr>
                  <td>1,012</td>
                  <td>taciti</td>
                  <td>sociosqu</td>
                  <td>ad</td>
                  <td>litora</td>
                </tr>
                <tr>
                  <td>1,013</td>
                  <td>torquent</td>
                  <td>per</td>
                  <td>conubia</td>
                  <td>nostra</td>
                </tr>
                <tr>
                  <td>1,014</td>
                  <td>per</td>
                  <td>inceptos</td>
                  <td>himenaeos</td>
                  <td>Curabitur</td>
                </tr>
                <tr>
                  <td>1,015</td>
                  <td>sodales</td>
                  <td>ligula</td>
                  <td>in</td>
                  <td>libero</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
</div>
{% endblock %}

perc/templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}PERC | Home{% endblock %}

{% block page_content %}

    <div class="jumbotron">
      <div class="container">
        <h1>PMEL Environment Reports Console</h1>
          {% if current_user.is_authenticated %}
	        <p>Logged in user: <b>{{ current_user.login_name }}</b></p>
	        <p>Logged in since {{ moment(current_time).fromNow(refresh=True) }}.</p>
          {% else %}
	        <p> You are not currently logged in.</p>
	        <p>Local date and time: {{ moment(current_time).format('LLL') }}.</p>
          {% endif %}
        <p>The PERC "user defined parameters" feature is provided soley as a courtesy and
            DOES NOT authorize or encourage deviation from TO 00-20-14 Section 8 requirements.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Assets</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Locations</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Sessions</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
    </div>

{% endblock %}

perc/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}PERC | Login{% endblock %}

{% block navbar %}
	<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">PERC</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

        </div><!--/.nav-collapse -->
      </div>
    </nav>
{% endblock %}

{% block page_content %}
	<header id="header">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 class="text-center"> Console <small>Account Login</small></h1>
          </div>
        </div>
      </div>
    </header>
    
    <section id="main">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-md-offset-4">
	            {{ wtf.quick_form(form) }}
          </div>
        </div>
      </div>
    </section>
{% endblock %}

perc/templates/report.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}PERC | Report{% endblock %}

{% block page_content %}

    {% if current_user.is_authenticated %}
    <h1>Report Criteria</h1>
    <p>You are logged in as <b>{{ current_user.login_name }}</b>.</p>
    <div class="row">
        <div class="col-md-3">
            {{ wtf.quick_form(form) }}
        </div>

    </div>
    {% else %}
    <h1>Protected page</h1>
    <p>This page can only be viewed by logged in users.</p>
    <p> You are not currently logged in.</p>
    <p>Local date and time: {{ moment(current_time).format('LLL') }}.</p>
    {% endif %}


{% endblock %}

perc/templates/summary_report.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}PERC | Summary Report{% endblock %}

{% block page_content %}

    {% if current_user.is_authenticated %}

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 bg-info">
     <h1>Report Criteria</h1>
    <p>You are logged in as <b>{{ current_user.login_name }}</b>.</p>
        <p>Location: {{ loc_name }}</p>
        <p>Start Date: {{ start_date }}</p>
        <p>End Date: {{ end_date }}</p>
        <p>Temperature: {{ temperature }}</p>
        <p>Temperature Tolerance: {{ temp_tol }}</p>
        <p>Humidity: {{ humidity }}</p>
        <p>Humidity Tolerance: {{ humid_tol }}</p>
    </div>
    <div class="col-lg-2">

    </div>
    <div class="col-lg-6">
      <h1>Report Details</h1>
        <table class="table table-hover table-condensed table-striped table-bordered">
          {% for key, value in report_data.items() %}
            <tr>
              <th> {{ key }} </th>
              <td> {{ value[0] }} </td>
            </tr>
          {% endfor %}
        </table>
        <p>Report generated {{ moment(current_time).fromNow(refresh=True) }}.
    </div>
  </div>
</div>
    {% else %}
    <h1>Protected page</h1>
    <p>This page can only be viewed by logged in users.</p>
    <p> You are not currently logged in.</p>
    <p>Local date and time: {{ moment(current_time).format('LLL') }}.</p>
    {% endif %}


{% endblock %}